# Generated by Django 4.2 on 2025-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveloffer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='traveloffer',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='traveloffer',
            name='offer_type',
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='destinations',
            field=models.ManyToManyField(related_name='offers', to='tourism.destination', verbose_name='Destinations'),
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='hotels',
            field=models.ManyToManyField(related_name='offers', to='tourism.hotel', verbose_name='Hôtels'),
        ),
        migrations.AlterField(
            model_name='traveloffer',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par personne'),
        ),
        migrations.AlterField(
            model_name='traveloffer',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
