# Generated by Django 4.2 on 2025-08-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_remove_traveloffer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
