# Generated by Django 4.2 on 2025-07-04 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du service')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon_class', models.CharField(max_length=100, verbose_name="Classe d'icône")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Service Club',
                'verbose_name_plural': 'Services Club',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la destination')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('hotel_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="Étoiles de l'hôtel")),
                ('duration_days', models.IntegerField(verbose_name='Durée en jours')),
                ('duration_nights', models.IntegerField(verbose_name='Durée en nuits')),
                ('package_type', models.CharField(default='Tout inclus', max_length=100)),
                ('departure_city', models.CharField(max_length=100, verbose_name='Ville de départ')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix original')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix actuel')),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('icon_class', models.CharField(default='fas fa-umbrella-beach', max_length=100)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destination phare')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('tunisie', 'Tunisie'), ('espagne', 'Espagne'), ('grece', 'Grèce'), ('turquie', 'Turquie'), ('maroc', 'Maroc')], max_length=50)),
                ('departure_date', models.DateField(verbose_name='Date de départ')),
                ('duration', models.CharField(choices=[('3-4', '3-4 jours'), ('7', '1 semaine'), ('14', '2 semaines'), ('21', '3 semaines')], max_length=10, verbose_name='Durée')),
                ('travelers_count', models.IntegerField(verbose_name='Nombre de voyageurs')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recherche',
                'verbose_name_plural': 'Recherches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'offre")),
                ('offer_type', models.CharField(choices=[('discount', 'Réduction'), ('free_child', 'Enfant Gratuit'), ('last_minute', 'Dernière Minute'), ('early_booking', 'Réservation Anticipée')], max_length=20, verbose_name="Type d'offre")),
                ('badge_text', models.CharField(max_length=100, verbose_name='Texte du badge')),
                ('description', models.TextField(verbose_name='Description')),
                ('conditions', models.TextField(blank=True, verbose_name='Conditions')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valable jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Offre Spéciale',
                'verbose_name_plural': 'Offres Spéciales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_city', models.CharField(max_length=100, verbose_name='Ville du client')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Témoignage vedette')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-created_at'],
            },
        ),
    ]
