# Generated by Django 4.2 on 2025-07-08 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'hôtel")),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="Étoiles de l'hôtel")),
                ('description', models.TextField(blank=True, verbose_name="Description de l'hôtel")),
                ('amenities', models.TextField(blank=True, help_text='Séparez les équipements par des virgules', verbose_name='Équipements')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name="Image de l'hôtel")),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hôtel',
                'verbose_name_plural': 'Hôtels',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='destination',
            name='hotel_rating',
        ),
        migrations.AddField(
            model_name='destination',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='tourism.hotel', verbose_name='Hôtels'),
        ),
    ]
